In [18]:
import numpy as n
import pandas as d
import matplotlib.pyplot as lt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler

In [2]:
df = d.read_csv("subscription_prediction (1).xls")

In [3]:
df.head()

age          job   marital    education  default housing loan    contact  \
0   40       admin.   married     basic.6y       no      no   no  telephone   
1   56     services   married  high.school       no      no  yes  telephone   
2   41  blue-collar   married      unknown  unknown      no   no  telephone   
3   57    housemaid  divorced     basic.4y       no     yes   no  telephone   
4   39   management    single     basic.9y  unknown      no   no  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [4]:
df.shape

(10122, 21)

In [5]:
df['y']=df['y'].apply(lambda x : 1 if x =='yes' else 0)

In [6]:
df['y'].value_counts()

y
0    5482
1    4640
Name: count, dtype: int64

In [7]:
X = df.drop('y', axis=1)
y = df['y']
Xtrain, Xtest, ytrain, ytest = train_test_split(X,y, train_size=0.6, random_state=417)

In [8]:
Xtest.shape

(4049, 20)

train test and validate split

In [9]:
Xtest,xval,ytest, yval = train_test_split(Xtest, ytest, train_size=0.5, random_state=417)

In [10]:
Xtest.shape

(2024, 20)

In [11]:
xval.shape

(2025, 20)

In [12]:
knn = KNeighborsClassifier(n_neighbors=5)


In [13]:
# knn.fit(Xtrain, ytrain)  this will show an error as knn defined on numerical data...and there are so many strings columns in the training data.

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10122 entries, 0 to 10121
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             10122 non-null  int64  
 1   job             10122 non-null  object 
 2   marital         10122 non-null  object 
 3   education       10122 non-null  object 
 4   default         10122 non-null  object 
 5   housing         10122 non-null  object 
 6   loan            10122 non-null  object 
 7   contact         10122 non-null  object 
 8   month           10122 non-null  object 
 9   day_of_week     10122 non-null  object 
 10  duration        10122 non-null  int64  
 11  campaign        10122 non-null  int64  
 12  pdays           10122 non-null  int64  
 13  previous        10122 non-null  int64  
 14  poutcome        10122 non-null  object 
 15  emp.var.rate    10122 non-null  float64
 16  cons.price.idx  10122 non-null  float64
 17  cons.conf.idx   10122 non-null 

In [15]:
xtrainscaled=d.get_dummies(Xtrain, columns=['marital', 'education'], drop_first= True)

In [16]:
xtrainscaled

age            job  default housing loan    contact month day_of_week  \
5725   38     management  unknown     yes   no   cellular   apr         fri   
2201   43  self-employed  unknown     yes   no  telephone   jun         tue   
8962   36         admin.       no      no   no   cellular   mar         mon   
156    32     technician       no      no   no  telephone   may         wed   
4405   37     technician       no      no   no   cellular   aug         tue   
...   ...            ...      ...     ...  ...        ...   ...         ...   
8270   54         admin.       no     yes   no   cellular   sep         tue   
4717   43     management       no     yes   no   cellular   nov         tue   
4263   31     technician  unknown     yes   no   cellular   aug         fri   
7009   29         admin.       no     yes   no   cellular   may         wed   
2617   32         admin.       no      no   no   cellular   jul         mon   

      duration  campaign  ...  marital_married  marital_single  \
5725       143         1  ...             True           False   
2201       363         4  ...            False           False   
8962       409         1  ...            False            True   
156        245         1  ...            False            True   
4405       277         2  ...            False            True   
...        ...       ...  ...              ...             ...   
8270        82         1  ...             True           False   
4717        99         1  ...             True           False   
4263      1123         2  ...            False            True   
7009       443         7  ...            False            True   
2617        79         2  ...            False            True   

     marital_unknown  education_basic.6y  education_basic.9y  \
5725           False               False               False   
2201           False               False               False   
8962           False               False               False   
156            False               False               False   
4405           False               False               False   
...              ...                 ...                 ...   
8270           False               False               False   
4717           False               False               False   
4263           False               False               False   
7009           False               False               False   
2617           False               False               False   

      education_high.school  education_illiterate  \
5725                   True                 False   
2201                  False                 False   
8962                  False                 False   
156                   False                 False   
4405                  False                 False   
...                     ...                   ...   
8270                  False                 False   
4717                  False                 False   
4263                  False                 False   
7009                   True                 False   
2617                  False                 False   

      education_professional.course  education_university.degree  \
5725                          False                        False   
2201                          False                         True   
8962                          False                         True   
156                            True                        False   
4405                          False                         True   
...                             ...                          ...   
8270                          False                        False   
4717                           True                        False   
4263                          False                         True   
7009                          False                        False   
2617                          False                         True   

      education_unknown  
5725           

In [17]:
xtrainscaled=xtrainscaled[['age','marital_married', 'pdays']]

In [24]:
xtrainscaled.head()

age  marital_married  pdays
5725   38             True    999
2201   43            False    999
8962   36            False    999
156    32            False    999
4405   37            False    999

In [20]:
scaler = MinMaxScaler()

In [21]:
scaler.fit(xtrainscaled)

MinMaxScaler()

In [23]:
scaler.min_

array([-0.22666667,  0.        ,  0.        ])

In [26]:
n1 = scaler.transform(xtrainscaled)

In [27]:
n1
d2=d.DataFrame(n1,columns=xtrainscaled.columns)
d2.head()

age  marital_married  pdays
0  0.280000              1.0    1.0
1  0.346667              0.0    1.0
2  0.253333              0.0    1.0
3  0.200000              0.0    1.0
4  0.266667              0.0    1.0

now working with xval to scale it

In [28]:
Xtest.head()
Xvalscaled=d.get_dummies(xval,columns=["marital","education"],drop_first=True)
Xvalscaled=Xvalscaled[["age","marital_married","pdays"]]
Xvalscaled=scaler.transform(Xvalscaled)


In [29]:
Xvalscaled[0:3]

array([[0.48      , 1.        , 1.        ],
       [0.22666667, 1.        , 1.        ],
       [0.50666667, 0.        , 1.        ]])

In [30]:
knn=KNeighborsClassifier(n_neighbors=5)

In [31]:
knn.fit(d2,ytrain)

KNeighborsClassifier()

In [32]:
knn.predict(Xvalscaled)

c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1, 0, 0, ..., 0, 1, 1], dtype=int64)

In [33]:
knn.score(Xvalscaled,yval)

c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


0.6172839506172839